(() => {
  'use strict';
  const $ = (s, root = document) => root.querySelector(s);
  const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const colors = { School: '#a78bfa', Work: '#7bb9ff', Personal: '#f2c978', Health: '#62e3bd', Social: '#f39bbb', Other: '#9ca9bc' };
  const storagePrefix = 'jarvis-calendar:';
  const idParam = new URLSearchParams(location.search).get('profile');
  const importedLink = location.hash.startsWith('#profile=') ? location.hash.slice(9) : '';
  const decode = value => { try { return JSON.parse(decodeURIComponent(escape(atob(value.replace(/-/g, '+').replace(/_/g, '/'))))); } catch { return null; } };
  const encode = value => btoa(unescape(encodeURIComponent(JSON.stringify(value)))).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  const newId = () => Math.random().toString(36).slice(2, 8).toUpperCase() + '-' + Math.random().toString(36).slice(2, 6).toUpperCase();
  const validData = data => data && Array.isArray(data.items) && typeof data.name === 'string';
  let profileId = idParam || localStorage.getItem(storagePrefix + 'active-profile-id') || newId();
  let sharedData = importedLink ? decode(importedLink) : null;
  if (!validData(sharedData)) sharedData = null;
  let data = sharedData || (() => { try { return JSON.parse(localStorage.getItem(storagePrefix + profileId)); } catch { return null; } })();
  if (!validData(data)) data = { name: '', items: [] };
  let activeMonth = new Date();
  let voiceRecognition = null;
  let voiceEnabled = false;
  let voiceRestartTimer;
  let toastTimer;
  const save = () => { try { localStorage.setItem(storagePrefix + 'active-profile-id', profileId); localStorage.setItem(storagePrefix + profileId, JSON.stringify(data)); } catch { toast('Storage is full. Export your profile to keep a backup.'); } };
  const dateAt = item => new Date(`${item.date}T${item.time || '23:59'}:00`);
  const sortedItems = () => data.items.filter(x => x && x.title && x.date).sort((a,b) => dateAt(a)-dateAt(b));
  const formatDate = (date, options = { weekday:'short', month:'short', day:'numeric' }) => new Intl.DateTimeFormat(undefined, options).format(date);
  const localDateString = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
  const timeLabel = item => item.time ? new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(dateAt(item)) : 'All day';
  const remaining = item => Math.max(0, dateAt(item) - Date.now());
  const durationText = item => { let ms = remaining(item); const days = Math.floor(ms/86400000); ms %= 86400000; const hours=Math.floor(ms/3600000); const mins=Math.floor((ms%3600000)/60000); if(days) return `<strong>${days}</strong> day${days===1?'':'s'} <strong>${hours}</strong> hr`; if(hours) return `<strong>${hours}</strong> hr <strong>${mins}</strong> min`; if(mins) return `<strong>${mins}</strong> min`; return '<strong>Now</strong>'; };
  const esc = str => String(str ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function toast(message) { const node=$('#toast'); node.textContent=message; node.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>node.classList.remove('show'),2600); }
  function render() {
    const now = new Date();
    $('#clock').innerHTML = `${new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',hour12:false}).format(now)}<span>${new Intl.DateTimeFormat(undefined,{second:'2-digit'}).format(now)}</span>`;
    $('#full-date').textContent = formatDate(now,{weekday:'long',month:'long',day:'numeric',year:'numeric'});
    $('#timezone').textContent = Intl.DateTimeFormat().resolvedOptions().timeZone?.split('/').pop()?.replaceAll('_',' ').toUpperCase() || 'LOCAL';
    $('#today-label').textContent = formatDate(now,{weekday:'long',month:'long',day:'numeric'}).toUpperCase();
    $('#greeting').textContent = now.getHours()<12?'morning':now.getHours()<17?'afternoon':'evening';
    const name = data.name.trim(); $('#hello-name').textContent = name || 'there'; $('#profile-label').textContent = name || 'My profile'; $('#profile-avatar').textContent = (name || 'J').slice(0,1).toUpperCase();
    const upcoming=sortedItems().filter(x=>!x.completed&&dateAt(x)>=new Date(now.getFullYear(),now.getMonth(),now.getDate()));
    const events=upcoming.filter(x=>x.type!=='homework'); const homework=upcoming.filter(x=>x.type==='homework');
    $('#event-count').textContent=events.length; $('#homework-count').textContent=homework.length;
    $('#countdown-total').textContent=upcoming.length;
    renderNext(upcoming[0]); renderCountdowns(upcoming.slice(0,6)); renderAgenda(upcoming.slice(0,7)); renderHomework(homework.slice(0,5));
    $('#homework-summary').textContent=homework.length?`${homework.length} item${homework.length===1?'':'s'} coming up`:'Nothing due soon';
    $('#homework-meter-fill').style.width=homework.length?`${Math.min(100,homework.filter(x=>x.completed).length/homework.length*100)}%`:'0%';
    if($('#calendar-modal').classList.contains('open')) renderEditorList();
  }
  function renderNext(item) {
    if (!item) { $('#next-up-content').innerHTML='<div class="next-date-box">✦</div><div><div class="next-title">Nothing on the horizon</div><div class="next-meta">Add an event to get started</div></div>'; $('#next-foot-label').textContent='Your schedule is clear'; $('#next-counter').textContent=''; $('#next-progress').style.width='0%'; return; }
    const d=dateAt(item); $('#next-up-content').innerHTML=`<div class="next-date-box"><strong>${d.getDate()}</strong>${formatDate(d,{month:'short'}).toUpperCase()}</div><div><div class="next-title">${esc(item.title)}</div><div class="next-meta">${formatDate(d,{weekday:'long'})} · ${esc(timeLabel(item))}</div></div>`;
    $('#next-foot-label').textContent=item.type==='homework'?'Homework deadline':'Time until it starts'; $('#next-counter').innerHTML=durationText(item).replace(/<[^>]*>/g,'');
    const total=Math.max(3600000,d-Date.now()); $('#next-progress').style.width=`${Math.max(4,Math.min(100,(1-remaining(item)/Math.max(total,86400000))*100))}%`;
  }
  function renderCountdowns(items) {
    const node=$('#countdown-grid'); if(!items.length){node.innerHTML='<div class="empty-card">Your calendar is clear. Add an event or homework to see a countdown here.</div>';return;}
    node.innerHTML=items.map(item=>{const d=dateAt(item),color=colors[item.category]||colors.Other,kind=item.type==='homework'?'Homework':item.category||'Event';return `<article class="countdown-card" style="--accent:${color}"><div class="countdown-head"><span class="category-label"><i class="category-dot"></i>${esc(kind)}</span><span class="countdown-date">${formatDate(d,{month:'short',day:'numeric'})} · ${esc(timeLabel(item))}</span></div><div class="countdown-title" title="${esc(item.title)}">${esc(item.title)}</div><div class="countdown-time">${durationText(item)}</div></article>`;}).join('');
  }
  function renderAgenda(items) {
    const node=$('#agenda-list'); if(!items.length){node.innerHTML='<div class="empty-card">Nothing scheduled yet. Add your first event with the Calendar button.</div>';return;}
    node.innerHTML=items.map(item=>{const d=dateAt(item),color=colors[item.category]||colors.Other;return `<div class="agenda-row" style="--accent:${color}"><div class="agenda-date"><strong>${d.getDate()}</strong>${formatDate(d,{month:'short'})}</div><i class="agenda-mark"></i><div><div class="agenda-title">${esc(item.title)}</div><div class="agenda-sub">${esc(timeLabel(item))}${item.notes?' · '+esc(item.notes):''}</div></div><span class="agenda-type">${item.type==='homework'?'HOMEWORK':esc(item.category||'EVENT').toUpperCase()}</span></div>`;}).join('');
  }
  function renderHomework(items) {
    const node=$('#homework-list');if(!items.length){node.innerHTML='<div class="homework-item"><span class="homework-check done">✓</span><div><div class="homework-item-title">All caught up</div><div class="homework-due">Your free time is yours</div></div></div>';return;}
    node.innerHTML=items.map(item=>`<div class="homework-item ${item.completed?'completed':''}"><button class="homework-check ${item.completed?'done':''}" data-toggle="${esc(item.id)}" aria-label="Mark ${esc(item.title)} ${item.completed?'incomplete':'complete'}">${item.completed?'✓':''}</button><div><div class="homework-item-title">${esc(item.title)}</div><div class="homework-due">Due ${formatDate(dateAt(item),{weekday:'short',month:'short',day:'numeric'})}${item.time?' · '+esc(timeLabel(item)):''}</div></div></div>`).join('');
    $$('[data-toggle]',node).forEach(button=>button.addEventListener('click',()=>{const item=data.items.find(x=>x.id===button.dataset.toggle);if(item){item.completed=!item.completed;save();render();}}));
  }
  function openModal(id){const modal=$(id);modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
  function closeModal(modal){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';}
  function resetForm(){ $('#item-form').reset(); $('#item-id').value=''; $('#item-date').value=localDateString(); $('#item-time').value=''; $('#form-heading').textContent='Add to your calendar'; $('#form-mode').textContent='NEW ITEM'; $('#form-symbol').textContent='✦'; $('#cancel-edit').classList.add('hidden'); }
  function editor() {const modal=$('#calendar-modal');openModal('#calendar-modal');resetForm();renderEditorList();setTab('items');}
  function renderEditorList(){const list=sortedItems();$('#editor-count').textContent=list.length;$('#editor-list-title').textContent=list.length?'Upcoming items':'No items yet';const node=$('#editor-list');if(!list.length){node.innerHTML='<div class="editor-empty">Your calendar is ready when you are.</div>';return;}node.innerHTML=list.map(item=>{const d=dateAt(item),color=colors[item.category]||colors.Other;return `<div class="editor-item" style="--accent:${color}"><i class="editor-item-mark"></i><div><div class="editor-item-title">${esc(item.title)}</div><div class="editor-item-meta">${item.type==='homework'?'Homework':esc(item.category||'Event')} · ${formatDate(d,{month:'short',day:'numeric',year:'numeric'})} · ${esc(timeLabel(item))}</div></div><div class="editor-item-actions"><button data-edit="${esc(item.id)}">Edit</button><button data-delete="${esc(item.id)}">Delete</button></div></div>`;}).join('');$$('[data-edit]',node).forEach(b=>b.onclick=()=>editItem(b.dataset.edit));$$('[data-delete]',node).forEach(b=>b.onclick=()=>deleteItem(b.dataset.delete));}
  function editItem(id){const item=data.items.find(x=>x.id===id);if(!item)return;$('#item-id').value=item.id;$('#item-title').value=item.title;$('#item-type').value=item.type||'event';$('#item-date').value=item.date;$('#item-time').value=item.time||'';$('#item-category').value=item.category||'Personal';$('#item-notes').value=item.notes||'';$('#form-heading').textContent='Edit your item';$('#form-mode').textContent='EDIT ITEM';$('#form-symbol').textContent=item.type==='homework'?'✓':'✦';$('#cancel-edit').classList.remove('hidden');$('#item-title').focus();}
  function deleteItem(id){const item=data.items.find(x=>x.id===id);if(!item)return;if(!confirm(`Delete “${item.title}”?`))return;data.items=data.items.filter(x=>x.id!==id);save();render();renderEditorList();toast('Item deleted.');}
  function setTab(tab){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#editor-layout').classList.toggle('hidden',tab!=='items');$('#month-panel').classList.toggle('hidden',tab!=='calendar');if(tab==='calendar')renderMonth();}
  function renderMonth(){const y=activeMonth.getFullYear(),m=activeMonth.getMonth();$('#month-name').textContent=new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(activeMonth);const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),node=$('#month-grid');node.innerHTML=['SUN','MON','TUE','WED','THU','FRI','SAT'].map(x=>`<div class="month-weekday">${x}</div>`).join('');for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-'),count=data.items.filter(x=>x.date===key).length;node.insertAdjacentHTML('beforeend',`<div class="month-day ${d.getMonth()!==m?'other':''} ${d.toDateString()===new Date().toDateString()?'today':''} ${count?'has-items':''}" data-day="${key}">${d.getDate()}${count?`<div class="month-item-count">${count} item${count>1?'s':''}</div>`:''}</div>`);}$$('[data-day]',node).forEach(cell=>cell.onclick=()=>{setTab('items');resetForm();$('#item-date').value=cell.dataset.day;$('#item-title').focus();});}
  function exportProfile(download=true){const blob=new Blob([JSON.stringify({version:1,profileId,name:data.name,items:data.items},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);if(download){const a=document.createElement('a');a.href=url;a.download=`jarvis-calendar-${profileId.toLowerCase()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}return url;}
  async function importProfile(file){try{const parsed=JSON.parse(await file.text());if(!validData(parsed))throw new Error('This file is not a Jarvis Calendar profile.');data={name:parsed.name.slice(0,32),items:parsed.items.filter(x=>x&&x.title&&x.date).map(x=>({...x,id:x.id||newId()}))};if(parsed.profileId)profileId=parsed.profileId;history.replaceState(null,'',`${location.pathname}?profile=${encodeURIComponent(profileId)}`);save();render();$('#profile-id-input').value=profileId;closeModal($('#profile-modal'));toast('Profile imported successfully.');}catch(e){toast(e.message||'Could not import this file.');}}
  function summaryText(){const next=sortedItems().filter(x=>dateAt(x)>=Date.now()).slice(0,5);if(!next.length)return 'You have nothing upcoming. Enjoy the breathing room.';return `You have ${next.length===1?'one upcoming item':`${next.length} upcoming items`}. `+next.map((item,i)=>{const ms=remaining(item),d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000);const when=d?`in ${d} day${d===1?'':'s'}${h?` and ${h} hour${h===1?'':'s'}`:''}`:h?`in ${h} hour${h===1?'':'s'}`:'soon';return `${i?'Next, ':''}${item.title}, ${when}`;}).join('. ')+'.';}
  function speakSummary(){const text=summaryText();if('speechSynthesis'in window){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.rate=.96;speechSynthesis.speak(utterance);}toast(text);}
  function setupVoice(){const Rec=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Rec){$('#voice-hint').textContent='Voice recognition is not available in this browser. Use the button for a spoken summary.';$('#voice-toggle').onclick=speakSummary;$('#voice-status').classList.add('error');$('#voice-status span').textContent='Voice recognition unavailable';return;}voiceRecognition=new Rec();voiceRecognition.continuous=true;voiceRecognition.interimResults=true;voiceRecognition.lang=navigator.language||'en-US';voiceRecognition.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal&&/hey\s+jarvis/i.test(e.results[i][0].transcript)){speakSummary();}}};voiceRecognition.onerror=e=>{if(e.error==='not-allowed'||e.error==='service-not-allowed'){voiceEnabled=false;setVoiceStatus('error','Microphone permission needed');$('#voice-toggle').classList.remove('active');$('#voice-hint').textContent='Allow microphone access in your browser to enable listening.';}else if(e.error!=='no-speech'&&e.error!=='aborted'){setVoiceStatus('error','Voice paused');}};voiceRecognition.onend=()=>{if(voiceEnabled){clearTimeout(voiceRestartTimer);voiceRestartTimer=setTimeout(()=>{try{voiceRecognition.start();}catch{}},350);}};$('#voice-toggle').onclick=()=>{if(voiceEnabled){voiceEnabled=false;clearTimeout(voiceRestartTimer);try{voiceRecognition.stop();}catch{}$('#voice-toggle').classList.remove('active');setVoiceStatus('','Voice is off');return;}voiceEnabled=true;$('#voice-toggle').classList.add('active');setVoiceStatus('listening','Listening for “Hey Jarvis”');$('#voice-hint').textContent='Say “Hey Jarvis” for your upcoming schedule.';try{voiceRecognition.start();}catch{voiceEnabled=false;setVoiceStatus('error','Could not start microphone');}};}
  function setVoiceStatus(kind,text){const n=$('#voice-status');n.className='voice-status '+kind; n.querySelector('span').textContent=text;}
  const tips=['Small steps today make tomorrow easier.','A five minute start is still a start.','Leave a little room between plans to reset.','Future you appreciates a note with the details.','Pick the one thing that would make today feel complete.'];let tipIndex=Math.floor(Math.random()*tips.length);
  function init(){
    if(!idParam||idParam!==profileId)history.replaceState(null,'',`${location.pathname}?profile=${encodeURIComponent(profileId)}`);
    save();render();setInterval(render,1000);$('#daily-tip').textContent=tips[tipIndex];$('#next-tip').onclick=()=>{tipIndex=(tipIndex+1)%tips.length;$('#daily-tip').textContent=tips[tipIndex];};
    $('#open-calendar').onclick=editor;$('#add-event-shortcut').onclick=()=>{editor();$('#item-type').value='event';$('#item-title').focus();};$('#add-homework').onclick=$('#add-homework-bottom').onclick=()=>{editor();$('#item-type').value='homework';$('#item-category').value='School';$('#item-title').focus();};$('#view-all-button').onclick=editor;
    $('#item-form').onsubmit=e=>{e.preventDefault();const id=$('#item-id').value||newId();const item={id,title:$('#item-title').value.trim(),type:$('#item-type').value,date:$('#item-date').value,time:$('#item-time').value,category:$('#item-category').value,notes:$('#item-notes').value.trim(),completed:false};if(!item.title||!item.date)return;const index=data.items.findIndex(x=>x.id===id);if(index>=0){item.completed=data.items[index].completed;data.items[index]=item;}else data.items.push(item);save();render();renderEditorList();resetForm();toast(index>=0?'Changes saved.':'Added to your calendar.');};$('#cancel-edit').onclick=resetForm;
    $$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.closest('.modal-backdrop')));$$('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m);}));document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal-backdrop.open').forEach(closeModal);});$$('.tab').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('#month-prev').onclick=()=>{activeMonth.setMonth(activeMonth.getMonth()-1);renderMonth();};$('#month-next').onclick=()=>{activeMonth.setMonth(activeMonth.getMonth()+1);renderMonth();};
    $('#profile-button').onclick=$('#profile-avatar').onclick=()=>{openModal('#profile-modal');$('#name-input').value=data.name;$('#profile-id-input').value=profileId;};$('#profile-form').onsubmit=e=>{e.preventDefault();data.name=$('#name-input').value.trim();save();render();closeModal($('#profile-modal'));toast('Profile saved.');};$('#new-profile-id').onclick=()=>{profileId=newId();history.replaceState(null,'',`${location.pathname}?profile=${profileId}`);$('#profile-id-input').value=profileId;save();toast('New profile ID created.');};
    $('#copy-link').onclick=async()=>{const url=`${location.origin}${location.pathname}?profile=${encodeURIComponent(profileId)}#profile=${encode(data)}`;try{await navigator.clipboard.writeText(url);toast('Share link copied. It contains a snapshot of your profile.');}catch{prompt('Copy this profile link:',url);}};$('#profile-export').onclick=()=>exportProfile(true);$('#export-button').onclick=()=>exportProfile(true);$('#profile-import').onchange=e=>{if(e.target.files[0])importProfile(e.target.files[0]);e.target.value='';};setupVoice();
  }
  init();
})();
